#!/usr/bin/env bash
source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
EExec_verbose_msg $(echo_id eexec_program)
unset eexec_program
#export eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

trap_exit_msg=

# Useful traps
on_exit()
{
    local rc="$?"
    local signum="${1-}"; shift

    echo "on_exit: rc: $rc; ${trap_exit_msg}"
}

on_error()
{
    local rc="${1-}"; shift

    echo "on_exit: rc: $rc; ${trap_exit_msg}"
    trap '' 0
}

#
# template ends.
########################################################################

#$ sed -b -e "s/192.168.0.30/192.168.1.30/" \
#-e "s/192.168.0.19/192.168.1.19/" \
#u-boot.img > u-boot-edit.img
#$ cat IP.sed
#s/192.168.000.030/192.168.001.030/
#s/192.168.000.019/192.168.001.019/

[ -n "${1-}" ] && {
    IMG_FILE="${1-}"
}

: ${GS_ORIG_ADDR:=192.168.001.030}
: ${VH_ORIG_ADDR:=192.168.001.019}

# This addr was given to my laptop by DHCP.
: ${GS_NEW_ADDR:=192.168.114.153}
: ${VH_NEW_ADDR:=192.168.114.037}
: ${IMG_FILE:=u-boot.img}


EExec sed -r -b -f - "${IMG_FILE}" <<EOF
s/${GS_ORIG_ADDR}/${GS_NEW_ADDR}/
s/${VH_ORIG_ADDR}/${VH_NEW_ADDR}/
EOF
