/* Copyright 2011 Google Inc. All Rights Reserved. */ (function(){var b=null,i=i||{};if(LEAPFROG_MODE)tblf.module.provide("tblf.translationary"),tblf.D=i;i.w=100;i.b="dict-chrome-ex";i.c=!1;i.v=RegExp("<[^>]*>","g");i.z=RegExp("[<>]","g");i.j="\" ' ( ) , - . / 1 2 2011 : ? a about and are as be but com for from have i in is it like may more my next not of on search that the this to was when with you your".split(" ");i.A="http://www.google.com/dictionary";i.options={};i.C=0;i.g=b;i.f=-1;
i.u=function(a){a=a.replace(i.v,"");a=a.replace(i.z,"");return a=a.substring(0,i.w).toLowerCase()};i.contains=function(a,d){for(var c=0,e=a.length;c<e;c++)if(d==a[c])return!0;return!1};i.a=function(a){return JSON.stringify(a,b,"  ")};i.s=function(){i.options=JSON.parse(window.localStorage.options)};i.p=function(a,d,c){a.type=="initialize"&&(a={instanceId:i.C++,leapfrogServerUrl:LEAPFROG_MODE?LEAPFROG_SERVER_URL:""},c(a))};
i.q=function(a,d,c){if(a.type=="options")LEAPFROG_MODE?(a={language:"en"},a.popupDblclick=tblf.localStorage.getItem("pref-translationary-enable"),a.popupDblclickKey="none",a.popupSelect="false",a.enableHttps=tblf.localStorage.getItem("pref-translationary-enable-https"),c({options:a})):c({options:i.options})};
i.o=function(a,d,c){if(!(a.type!="fetch_raw"&&a.type!="fetch_html")){_gaq&&_gaq.push(["_trackEvent","lookup",a.type]);i.g!=b&&i.f!=a.instanceId&&chrome.tabs.sendRequest(i.g.id,{type:"hide",instanceId:i.f});i.g=d.tab;i.f=a.instanceId;var d=i.u(a.query),e={request:a,sanitizedQuery:d,dictResponse:b,translateResponse:b,numResponses:0,callback:c},c="pr,de";a.type=="fetch_html"&&(c="pr,de,sy");google.language.define(d,i.options.language,i.options.language,function(a){i.d(a,"dict",e)},{restricts:c});LEAPFROG_MODE||
(i.t(d,function(a){i.d(a,"translate",e)}),chrome.tabs.getSelected(b,function(a){window.setTimeout(function(){i.d({lang:"unknown"},"tabLang",e)},800);chrome.tabs.detectLanguage(a.id,function(a){i.d({lang:a},"tabLang",e)})}))}};i.t=function(a,d){var c=new XMLHttpRequest;c.open("GET","https://clients5.google.com/translate_a/t?client="+i.b+"&sl=auto&tl="+i.options.language+"&q="+a,!0);c.onreadystatechange=function(){if(c.readyState==4)try{d(JSON.parse(c.responseText))}catch(a){d(b)}};c.send()};
i.k=function(a){return a=="he"?"iw":a};
i.d=function(a,d,c){if(d=="dict")c.dictResponse=a;else if(d=="translate")c.translateResponse=a;else{if(c.tabLang)return;c.tabLang=i.k(a.lang)}a=3;LEAPFROG_MODE&&(a=1);c.numResponses++;if(c.numResponses==a){a=i.l(c.dictResponse);d=i.h(c.translateResponse,!0);i.c&&(console.log("dictResponse:"),console.log(i.a(c.dictResponse)),console.log("definitionObj:"),console.log(i.a(a)),console.log("translateResponse:"),console.log(i.a(c.translateResponse)),console.log("translationObj:"),console.log(i.a(d)));var e=
b;if(c.translateResponse&&c.translateResponse.ld_result&&(e=c.translateResponse.ld_result.srclangs))for(var f=0,g=e.length;f<g;f++)e[f]=e[f].toLowerCase();f=!1;i.c&&d&&(console.log("srcLang="+d.srcLang.toLowerCase()),console.log("tabLang="+c.tabLang.toLowerCase()),console.log("optLang="+i.options.language.toLowerCase()));if(!a||a.type!="licensedDef"){var g=i.options.language.toLowerCase(),h=d&&d.srcLang.toLowerCase()!=g;if(h&&e&&!i.contains(e,g)||!a&&h)f=!0}e=f?"translation":"definition";!a&&!d&&
(e="none");_gaq&&_gaq.push(["_trackEvent","lookup","type_"+e]);e="http://translate.google.com/translate_t?source="+i.b+"&sl=auto&tl="+i.options.language+"&q="+encodeURIComponent(c.sanitizedQuery);g="http://www.google.com/search?source="+i.b+"&defl="+i.options.language+"&hl="+i.options.language+"&q="+encodeURIComponent(c.sanitizedQuery)+"&tbo=1&tbs=dfn:1";if(c.request.type=="fetch_html")a="",a=f?i.n(c.translateResponse,e):i.m(c.dictResponse,g),a={eventKey:c.request.eventKey,sanitizedQuery:c.sanitizedQuery,
html:a};else{h=b;if(f&&d)h=d,h.moreUrl=e;else if(a)h=a,h.moreUrl=g;h&&!h.prettyQuery&&(h.prettyQuery=c.sanitizedQuery);a=!1;if(!LEAPFROG_MODE&&(i.options.popupDblclick=="true"&&i.options.popupDblclickKey=="none"||i.options.popupSelect=="true"&&i.options.popupSelectKey=="none")&&i.contains(i.j,c.sanitizedQuery))a=!0;a={eventKey:c.request.eventKey,sanitizedQuery:c.sanitizedQuery,meaningObj:h,showOptionsTip:a};i.c&&(console.log("finalResponse:"),console.log(i.a(a)))}c.callback(a)}};
i.h=function(a,d){if(!a||a.sentences[0].orig.toLowerCase()==a.sentences[0].trans.toLowerCase())return b;var c=window["gdx.LANG_MAP"][a.src.toLowerCase()];c||(c=a.src);return{type:"translation",meaningText:function(){var c=a.sentences[0].orig.toLowerCase(),f=a.sentences[0].trans.toLowerCase(),g=f;if(d&&a.dict&&a.dict.length>0)for(var h=0,j=a.dict.length;h<j;h++)for(var l=a.dict[h],k=0,n=0,o=l.terms.length;n<o&&k<2;n++){var m=l.terms[n].toLowerCase();m.length>0&&m!=c&&m!=f&&(g+=", "+m,k++)}return g}(),
attribution:"Translated from "+c,srcLang:a.src}};i.e=function(a,d){for(var c=0,e;e=a[c];c++)if(e.type&&e.type==d&&e.text)return e.text;return""};i.i=function(a){if(!a||a.length==0)return b;for(var d=0,c;c=a[d];d++)for(var e=0,f;f=c.entries[e];e++)if(f.type=="meaning"&&f.terms&&f.terms.length>0){var g=i.e(f.terms,"text");if(g)return a=i.e(c.terms,"sound").replace("http://","https://"),{prettyQuery:i.e(c.terms,"text"),meaningText:g,audio:a,attribution:i.e(f.terms,"url")}}return b};
i.l=function(a){if(!a||a.error)return b;var d=i.i(a.primaries);d?(d.attribution="",d.type="licensedDef"):(d=i.i(a.webDefinitions))&&(d.type="webDef");return d};
i.n=function(a,d){var c=i.h(a,!1);if(!c)return"";var c='<div class="translate-main">'+c.meaningText+'</div><div class="translate-attrib">('+c.attribution+")</div>",e="";if(a.dict&&a.dict.length>0)for(var e='<h3 class="dct-tl">Translated definitions</h3>',f=0,g=a.dict.length;f<g;f++){var h=a.dict[f];e+="<b>"+h.pos+"</b><ol>";for(var j=0,l=h.terms.length;j<l;j++){var k=h.terms[j];k.length>0&&(e+="<li>"+k+"</li>")}e+="</ol>"}return c+e+('<br><div class="translate-powered">Powered by <a href="'+d+'" class="translate-link">Google Translate</a></div><br>')};
i.m=function(a,d){if(!a||a.error)return"";var c=google.language.dictionary.createResultHtml(a),e=document.createElement("div");e.innerHTML=c;for(var c=e.getElementsByTagName("a"),f=c.length-1;f>=0;f--){var g=c[f];if(g.innerText=="Google Dictionary"&&g.href.lastIndexOf(i.A,0)==0)g.href=d}return e.innerHTML};
i.r=function(a){var d={};d.language=a.language||"en";var c=function(a,c){return a=="true"||a=="false"?a:a==!0?"true":a==!1?"false":c};d.popupDblclick=c(a.popupDblclick,"true");d.popupSelect=c(a.popupSelect,"false");d.enableHttps=c(a.enableHttps,"true");d.popupDblclickKey=a.popupDblclickKey||"none";d.popupSelectKey=a.popupSelectKey||"ctrl";if(a.popupMode)if(a.popupMode=="popup_disabled")d.popupDblclick="false";else if(a.popupMode=="popup_key_ctrl")d.popupDblclickKey="ctrl",d.popupSelect="true",d.popupSelectKey=
"ctrl";return d};i.B=function(){dict_api.load("https://clients5.google.com?client="+i.b,"1","en");var a=window.localStorage.options,d={};a&&(d=JSON.parse(a));i.options=i.r(d);window.localStorage.options=JSON.stringify(i.options);i.c&&(console.log("gdx.options:"),console.log(i.a(i.options)));chrome.extension.onRequest.addListener(i.p);chrome.extension.onRequest.addListener(i.q);chrome.extension.onRequest.addListener(i.o);window["gdx.updateOptions"]=i.s};LEAPFROG_MODE||i.B();})();
