#!/bin/sh

#source script-x
#set -x
# These were clobbering each other across hosts.
SSH_AGENT_RC="$HOME/.ssh/acmds.$HOSTNAME"
SSH_AGENT_RC_STDERR="${SSH_AGENT_RC}.stderr"
export SSH_AGENT_RC_umask=0077
export SSH_AGENT_RC_STDERR_umask=${SSH_AGENT_RC_umask}

dp_add_default_keys()
{
    ssh-add -l > /dev/null 2>&1
    local rc=$?
    case "$rc" in
        0) true;;               # Got some, hopefully all, default keys.
        1) ssh-add;;            # Agent up, no keys. Add defaults.
        *) false;;              # No agent
    esac
}

# Really start or connect to ssh agent
dp_start_ssh_agent()
{
    # Until I fix this whole concept.
    [ -n "${SSH_AGENT_PID}" ] && {
        ssh-add -l > /dev/null 2>&1
        local rc=$?
        [ "$rc" = 1 ] && {      # No keys
            ssh-add             # Add defaults
            [ -n "${DP_SSH_EXTRA_KEYS}" ] && {
                ssh-add "${DP_SSH_EXTRA_KEYS}"
            }
        }
    }
    return 0

#for now     #env | fgrep SSH
#for now     #echo_id SSH_AGENT_RC
#for now     # See if there's a running agent to which we are attached.
#for now     dp_add_default_keys && return 0

#for now     # See if we can attach to one started elsewhere.
#for now     [ -e "$SSH_AGENT_RC" ] && {
#for now         # Use last set of agent variables.
#for now         source "$SSH_AGENT_RC" || return 3
#for now         # Try to add keys.
#for now         dp_add_default_keys && return 0
#for now     }
#for now     # There isn't an agent already running that we can use, neither
#for now     # configured in this shell nor one whose configuration info is in the
#for now     # "$SSH_AGENT_RC"
#for now     # So start one and save the configuration variables.
#for now     ssh-agent | \fgrep -v echo >| "$SSH_AGENT_RC"
#for now     # set those variables.
#for now     source "$SSH_AGENT_RC" || return 3
#for now     # If we can't set the keys, we're doomed.
#for now     # Pass on the key command rc.
#for now     dp_add_default_keys
}

[ -n "${runme-}" -o "$(basename -- $0)" = dp-ssh-agent ] && {
    dp_start_ssh_agent
}

