version 4.0
set notitle
set showcmd
source ~/.exrc
set backup
set bex=.bak
set mouse=a
set softtabstop=8
set shiftwidth=8
set noexpandtab
colorscheme elflord
syntax off
set nohlsearch
set t_Co=0

set backupdir=~/droppings/editors/vim/backups//,/tmp//
set directory=~/droppings/editors/vim/backups//,/tmp//
set undodir=~/droppings/editors/vim/backups//,/tmp//
