version 4.0
set notitle
set showcmd
source ~/.exrc
set backup
set bex=.bak
set mouse=a
set softtabstop=4
set shiftwidth=4
set noexpandtab
colorscheme delek
set spell spelllang=en_us
set spellfile=~/.vim/spell/dp.utf-8.add
