#!/bin/bash

set -u

# Use "real" symlinks on Windwoes/cygwin.
# Set this unconditionally since it shouldn't hurt in a real environment.
# NB this doesn't work in a "Git Bash" since that is a minGW app, not cygwin.
export CYGWIN="winsymlinks:nativestrict"

EZEC=
: ${default_parent:=dpw}
: ${default_repo:=dpw/dpw}
: ${repo:="${default_parent}/$(basename ${PWD})";;
while (($# > 0 ))
do
    case "$1" in
        -n) EZEC="echo - ";;
        -r|--repo) shift; repo="$1";;
        -d|--default-repo) repo="${default_repo}";;
	-x)  set -x;;
	--) shift; break;;
        *) break;;
    esac
    shift
done

case "${repo}" in
    /*) repo=$(./dp-realpath -R ${HOME} ${repo});;
    *) ;;
esac

: ${reporc:=${repo}/.rc}

cd "${HOME}" || {
    echo "Cannot cd to home>${HOME}<"
    exit 1
} 1>&2

ln_dotrc()
{
    for fuckyou in "$@"
    do
	${EZEC} ln -s ".rc/${fuckyou}" ".${fuckyou}"
    done
}

repo_ln()
{
    for eatshit in "$@"
    do
        ${EZEC} ln -s "${repo}/${eatshit}" .
    done
}

cd "${HOME}"
${EZEC} ln -s "${repo}/DOTrc" .rc

# This should be compatible with exuberant-ctags since universal-ctags is the
# resurrection of exuberant-ctags.
${EZEC} ln -s ".rc/universal-ctags.conf" .ctags

repo_ln \
    bin \
    bin.exp \
    bin.primitive \
    yokel \
    etc \
    lib \
    lisp \
    xf86 \
    patches

ln_dotrc \
	alias \
	gdbinit \
	gitconfig \
	gitexclude \
	go \
	go.emacs \
	inputrc \
	lessrc \
	muttrc \
	mutt-colors \
	mutt-aliases \
	screenrc \
	vimrc \
        exrc \
	bash_logout \
        go.home \
        mailrc

#
# Reference all of the bash_completion code.
BASH_COMPLETION_DIR=.bash_completion.d
RC_BASH_COMPLETION_DIR=.rc/DOTbash_completions.d
SYS_BASH_COMPLETION_DIR=/usr/share/bash-completion
[ -d "${SYS_BASH_COMPLETION_DIR}" ] && {
    # This doesn't allow us to put new completion scripts in the standard
    # completion location.  ln -s "${SYS_BASH_COMPLETION_DIR}"
    # "${BASH_COMPLETION_DIR}"
    mkdir -p "${BASH_COMPLETION_DIR}"
    (
        cd "${BASH_COMPLETION_DIR}" || {
            echo 1>&2 "Could not cd to ${BASH_COMPLETION_DIR}"
            exit 1
        }
        ${EZEC} ln -s "${SYS_BASH_COMPLETION_DIR}"/* .
        ${EZEC} ln -s "../.rc/DOTbash_completions.d"/* .
    ) || {
        echo 1>&2 "Could not perform all bash completion setup operations."
        exit 1
    }
}

OEM_DIR="${HOME}/.oem-dot-files"
mkdir -p "${OEM_DIR}"
for f in .bash_login .bashrc .bash_profile
do
	[ -h "${f}" ] && continue
	oem_file_name="${OEM_DIR}/DOT${f}"
	[ -e "${oem_file_name}" ] || {
	    ${EZEC} mv "${f}" "${oem_file_name}"
	}
	${EZEC} ln -s .rc/bashrc $f
done

${EZEC} ln -s lisp .xemacs
${EZEC} ln -s .rc/procmailrc.vilya .procmailrc
${EZEC} ln -s lisp/Makefile .
${EZEC} mkdir var
${EZEC} mkdir var/log
${EZEC} mkdir log
(
	cd log
        ${EZEC} mkdir {boot,kde,login-rc,xemacs,shell-sessions}
        ${EZEC} mkdir auto-rotate-c5-50K
        ${EZEC} mkdir shell-sessions/home/dpanarit/log/shell-sessions
	${EZEC} ln -s auto-rotate-c5-50K procmail
)
${EZEC} mkdir -p "log/auto-rotate-c10-50K"
${EZEC} mkdir ipc
${EZEC} mkdir tmp
${EZEC} mkdir .screen
${EZEC} mkdir notes

droppings="droppings/bash_history \
droppings/editors/xemacs \
droppings/editors/xemacs/session-auto-saves.d \
droppings/editors/xemacs/tramp.d \
droppings/editors/xemacs/tramp.d/auto-saves.d \
droppings/editors/xemacs/xebacs.d \
droppings/editors/xemacs/ephemeral.d \
droppings/editors/xemacs/auto-saves.d \
droppings/persist/gdb_history \
droppings/persist/emacs-history"

for dropping in ${droppings}
do
  ${EZEC} mkdir -p "${dropping}"
done

echo 'Other new Linux installation actions:
1) samba: I need to find the old instructions for this.
2) kernel core pattern: 
   To /etc/sysctl.conf, add: kernel.core_pattern = %e-p:%p,u:%u,s:%s,t:%t.CR
3) in ~/bin/src: [automate this]
   1) gcc eko.cpp ../eko
   2) gcc utmpdump.c ../utmpdump
   +) gcc $f ../$(basename .c|.cpp|???)
'

echo "TODO! Try to link ~/.rc/xxx.<host> and then ~/.rc/xxx into ~"
