#!/usr/bin/env bash
# $Id: daily,v 1.61 2007/08/28 08:20:12 davep Exp $
#set -x

. $HOME/etc/crontab.rc

$HOME/bin.amd/amd-index-edc-linux

echo ""
echo "daily done $(date)"
echo "==========================="


