--- ./modules/viavoice/Makefile.ORIG	Tue Nov 26 16:45:30 2002
+++ ./modules/viavoice/Makefile	Tue Nov 26 16:45:55 2002
@@ -425,13 +425,13 @@
 
 
 %.x %.doc: %.c
-	$(SCWM_SRC_DIR)/scwm-snarf $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).x && \
+	$(SCWM_SRC_DIR)/scwm-snarf $< $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) > $(basename $<).x && \
 	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).doc \
 	|| { rm $(basename $<).x $(basename $<).doc ; false; }
 
 %.x %.doc: %.cc
 	CC=$(CXX) \
-	$(SCWM_SRC_DIR)/scwm-snarf -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).x && \
+	$(SCWM_SRC_DIR)/scwm-snarf $< -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) > $(basename $<).x && \
 	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).doc \
 	|| { rm $(basename $<).x $(basename $<).doc ; false; }
 
