#!/usr/bin/emv bash

source ~davep/.bashrc

#set -x
#exec >>"/tmp/davep.kde3rc.log" 2>&1
#echo "0>$0<"

source $HOME/xf86/basic_x_apps 108
source $HOME/xf86/Kclients.huan
korn &
# Needs reinstalled:       basket &
# Don't use it:  akregator &
kopete &
kwalletmanager &
