--- Makefile.ORIG	Thu May 22 12:37:49 2003
+++ Makefile	Thu May 22 12:39:01 2003
@@ -20,14 +20,14 @@
 ##
 
 prefix=/usr/local
-infodir=$(prefix)/info
+#infodir=$(prefix)/info
 
 ##
 ## Compile engines
 ##
 
-EMACS = emacs
-#EMACS = xemacs
+#EMACS = emacs
+EMACS = xemacs
 #EMACS = mule
 
 ##
@@ -36,13 +36,16 @@
 
 elispdir = $(prefix)/share/emacs/site-lisp/mew
 #elispdir  = $(prefix)/lib/$(EMACS)/site-lisp
+elispdir  = $(prefix)/lib/$(EMACS)/site-packages/lisp/mew
 #elispdir = $(prefix)/lib/emacs
+infodir=$(prefix)/lib/$(EMACS)/site-packages/info
 
 ##
 ## A directory where etc file will be installed.
 ##
 
-etcdir = $(prefix)/lib/$(EMACS)/etc/Mew
+#etcdir = $(prefix)/lib/$(EMACS)/etc/Mew
+etcdir = $(prefix)/lib/$(EMACS)/site-packages/etc/Mew
 
 ################################################################
 ##
