#!/bin/sh
# source me
gdmf_regexps=(
    "--egrep" "Error: LoadPlugin: couldn't load plugin library"
    "--egrep" 'ERROR: cannot aquire /tmp/asim\.X'
    "--egrep" 'ERROR: cannot find /home/scratch\.'
    "--egrep" 'Error opening.*\.so:.*lib.*not found'
    "--egrep" 'KeyError: .OUT.'
    "--egrep" 'RT_FAIL'
    "--egrep" '\(gdb\)'
    "--egrep" 'qemu: could not load kernel'
    "--egrep" 'something bad happened'
    "--hgrep" 'call stack'
    "--hgrep" 'stack trace'
    "--hgrep" 'surface_write_read:'
    "--hgrep" 'waiting for a connection on port [0-9]+'
)

# regexp=
# sep=
# set -- "${gdmf_regexps[@]}"
# echo "@>$@<"
# while (($# > 1))
# do
#   #echo "@>$@<"
#   shift
#   #echo "@>$@<"
#   regexp="${regexp}${sep}${1}"
#   sep="
# |"
# done
# echo_id regexp
  
