#!/bin/bash

set -u

: ${tty:=/dev/gumstix}
: ${baud:=115200}
: ${SCREEN_NAME:=gumstix-console}

while (($# > 0))
do
  case "${1}" in
      --tty) shift; tty-"${1}";;
      --baud) shift; baud="${1}";;
      --name) shift; SCREEN_NAME="${1}";;
      --) shift; break;;
      *) break;;
  esac
  shift
done

exec sudo screen -dR -t "${SCREEN_NAME}" -S "${SCREEN_NAME}" "${tty}" "${baud}"
