#!/bin/bash

cd $YOCTO_DIR/build/tmp/deploy/images
DEST=$HOME/inb/staging
: ${EZEC=}
: ${compare_p=t}
: ${UBOOT_IMG:="u-boot.img"}
: ${UBOOT_DST_NAME:="u-boot.img"}

while (($# > 0))
do
  case "$1" in
      -n) EZEC="echo -";;
      --no-compare) echo YOPP; compare_p=;
                    echo "compare_p>$compare_p<"
                    ;;
      --skuboot|--sku) UBOOT_IMG=skaion/u-boot.img
                       ;;
      --) shift; break;;
      *) break;;
  esac
  shift
done
echo "compare_p>$compare_p<"

FILES=(
    "MLO"
    "${UBOOT_IMG}"
    "uImage"
    "gumstix-console-image-vet-overo.ubi"
)

TAR_BALL="gumstix-console-image-vet-overo.tar.bz2"
ALL_FILES=("${FILES[@]}" "${TAR_BALL}")

exit_p=
for f in "${ALL_FILES[@]}"
do
  [ -e "${f}" ] || {
      echo "${f} does not exist."
      exit_p=t
  }
done 1>&2

[ "${exit_p}" = t ] && {
    echo "Some files were not found, nothing copied."
    exit 1
}

echo "compare_p>$compare_p<"
for f in "${ALL_FILES[@]}"
do
  dst="${DEST}/$(basename ${f})"
  echo "Copying: ${f} to ${dst}"
  $EZEC rsync -L -c "${f}" "${dst}"
  [ "${compare_p}" = "t" ] && {
      echo "Comparing: ${f} to ${dst}"
      $EZEC cmp "${f}" "${dst}" || {
          echo "failed: cmp ${f} ${dst}"
          exit 1
      } 1>&2
  }
done

