#!/bin/tcsh

# bin/t_make -clean
# bin/t_make -skiprtl
#( true || { echo "t_make -clean failed." ; exit 1 } echo "t_make -clean passed." ; true  || { echo "t_make -skiprtl failed." ; exit 1 }  echo "t_make -skiprtl passed." ) |& tee bin%t_make.`dp-std-timestamp`.out
# Mr Joy, yer csh sucks.
( bin/t_make -clean && bin/t_make -skiprtl ) | & tee make-`dp-std-timestamp`.out
