#!/usr/bin/env bash
set -u
progname="$(basename $0)"

prefix=""
leading_zeroes=""
width=''
assume_hex_p=t

while (($# > 0))
do
  case "$1" in
      --0x|-x) prefix="0x";;
      --0X|-X) prefix="0X";;
      --no-0x|--nox) prefix="";;
      -z|--zeroes) leading_zeroes="0";;
      --nz|--no-zeroes|--no0|--no-0) leading_zeroes=; width='';;
      --nh|--nx) assume_hex_p=;;
      -8|--long|--32) leading_zeroes="0"; width=8;;
      -w|--width) shift; width="${1}";;
      --) shift; break;;
      *) break;;
  esac
  shift
done

for n in "$@"
do
  [ -n "${assume_hex_p}" ]  && {
      case "${n}" in
          0[Xx]*) ;;
          *) n="0x${n}";;
      esac
  }
  printf "${prefix}%${leading_zeroes}${width}d\n" "${n}"
done
