#!/bin/sh

source script-x
set -u
progname="$(basename $0)"

[ -z "$DISPLAY" ] && {
    echo "DISPLAY variable is not set. Nothing I can do."
    exit 1
} 1>&2

# e.g. echo $DISPLAY --> o-xterm-33:39.0
disp=$(echo "$DISPLAY" | sed -rn 's/(^[^:]+)(:[0-9]+)(.*$)/\2/p')

[ -z "$disp" ] && {
    echo "Cannot extract display number from \$DISPLAY[$DISPLAY]."
    exit 2
} 1>&2

command="vncserver -kill $disp"
if [ "${1-}" = "-n" ]
then
    echo "{-}$command"
else
    $command
fi
