;;;
;;; 'global abbrevs are for automatic expansion, e.g. speling erors.
;;; 'common abbrevs are expected to be expanded by hand.
;;; @ todo... add mode to "properties" and then add to table for that mode.
;;; Stems of abbrev tables.  If just a symbol then construct a table name of
;;;  <sym>-abbrev-table
;;; 
(defconst dp-common-abbrevs
  '(
    (("wrt" "with respect to") dp-common)
    (("teh" "the") dp-common global)
    (("st" "such that" dp-common))
    (("wether" "whether") dp-common global)
    (("wheter" "whether") dp-common global)
    (("thru" "through") dp-common global)
    (("thot" "thought") dp-common global)
    (("tho" "though") dp-common global)
    (("dap" "David A. Panariti") dp-common) ; `dp' is NOT expanded.
    (("te" "there exists") dp-common)
    (("stl" "STL") dp-common global)
    (("mobo" "motherboard") dp-common)
    (("altho" "although") dp-common global)
;;    (("d3" "DooMIII"))		; a bit too general
    (("kb" "keyboard") dp-common)
    (("eg" "e.g.") dp-common global)
    (("qv" "q.v.") dp-common global)
    (("ie" "i.e.") dp-common global)    ; May give problems.
    (("nb" "N.B.") dp-common global)
    (("plz" "please") dp-common global)
;;    (("addr" "address"))
;;    (("addrs" "addresses"))
    ;;;;;;;("eo" "EO")
    (("sthg" "something") dp-common global)
    (("iir" "if I recall") dp-common global)
    (("Iir" "if I recall") dp-common global)
    (("IIR" "if I recall") dp-common global)
    (("appt" "appointment") dp-common)
    (("appts" "appointments") dp-common)
    (("ok" "OK") dp-common global)
    (("fo" "of") dp-common global)
    ;;;;;;;;;;;;;;;;;;;;;(("ts" "tag-space"))
    (("decl" "declaration") dp-common global)
    (("decls" "declarations") dp-common global)
    (("prob" "problem") dp-common)
    (("probs" "problems") dp-common)
    ;;;;;;;(("num" "number"))
    ;;;;;;;(("nums" "numbers"))
    ;;;;;;;(("kde" "KDE"))
    ;;;;;;;(("vnc" "VNC"))
    (("gui" "GUI") dp-common global)
    (("bup" "backup") dp-common global)
    (("bups" "backups") dp-common global)
    (("khz" "KHz") dp-common global)
    (("mhz" "MHz") dp-common global)
    (("ghz" "GHz") dp-common global)
    (("kbps" "Kbps") dp-common global)
    (("gbps" "Gbps") dp-common global)
    (("ns" "nS") dp-common)
    (("ms" "mS") dp-common)
    (("linux" "Linux") dp-common global)
    (("thier" "their") dp-common global)
    (("beleive" "believe") dp-common global)
    (("yopp" "YOPP!") dp-common)
    (("repos" "repository") dp-common)
    (("e2ei" "RSVP-E2E-IGNORE") dp-common)
    (("LARTC" "Linux Advanced Routing & Traffic Control HOWTO") dp-common)
    (("lartc" "Linux Advanced Routing & Traffic Control HOWTO") dp-common)
    (("pkt" "packet") dp-common)
    (("lenght" "length") dp-common global)
    (("recieve" "receive") dp-common global)
    (("reciever" "receiver") dp-common global)
    (("rxer" "receiver") dp-common global)
    (("rxor" "receiver") dp-common global)
    (("recv" "receive") dp-common)
    (("nic" "NIC") dp-common)
    (("tcp/ip" "TCP/IP") dp-common global)
    (("udp" "UDP") dp-common)
    (("q" "queue") dp-common)
    (("enq" "enqueue") dp-common)
    (("deq" "dequeue") dp-common)
    (("xmission" "transmission") dp-common global)
    (("xmit" "transmit") dp-common global)
    (("tx" "transmit") dp-common)
    (("rx" "receive") dp-common)
)
  "Aliases I like to have everywhere."
)

