var background=chrome.extension.getBackgroundPage(),featureArticleSupport={ar:true,bar:false,bg:false,cs:true,da:true,de:true,el:true,en:true,es:true,fa:false,fr:true,it:true,lt:false,he:true,hr:false,hu:true,ksh:false,ru:false,sv:true,tr:false,nds:false,nl:true,nn:false,no:false,pl:true,pt:true,sr:false,fi:false,zh:true,ja:true,ko:true,vi:true,uk:true};function startup(){setTimeout(loadwiki,100)}
function loadwiki(){if(!background.wikihistory||background.wikihistory.length==0){var a=document.getElementById("loadingpage");if(localStorage.showFeatureArticle=="true"){a=background.getCurrentLang();a=featureArticleSupport[a]?"http://"+a+".m.wikipedia.org":"http://en.m.wikipedia.org"}else{a.src="./welcome.html";return}}else{if(background.currentHistoryPosition>=background.wikihistory.length)background.currentHistoryPosition=background.wikihistory.length-1;a=background.wikihistory[background.currentHistoryPosition].url}displayURL(a)}
function displayURL(a){if(background.wikicache[a]){background.wikicache[a]=background.wikicache[a].replace(/<body style=['"].*?['"]/ig,"<body style='width:"+(parseInt(localStorage.pageWidth)-20)+"px' ");document.open();document.write(background.wikicache[a]);document.close();modifyPageAfterLoad();document.body.style.width=parseInt(localStorage.pageWidth)-20+"px";jQuery(document).triggerHandler("ready");document.onmouseup=function(d){createRightClickPopupBox(d)}}else{var b="http://"+a.match(/^http:\/\/(.*?).m/)[1]+
".m.wikipedia.org",c=new XMLHttpRequest;c.open("GET",a,true);c.onreadystatechange=function(){if(c.readyState==4){var d=c.responseText;if(d!=""){d=d.replace(/<link href=(['"])(\/.*?)(['"])/ig,"<link href=$1"+b+"$2$3").replace(/\bsrc=(['"])(\/.*?)(['"])/ig,"src=$1"+b+"$2$3").replace("<div class='message notice'>","<div style='display:none;' 'message notice'>").replace("<div id='searchbox'","<div style='display:none;' id='searchbox'").replace("id='footmenu'>","id='footmenu' style='display:none'>").replace(/<div class='mwm-message/ig,
"<div style='display: none' class='mwm-message").replace("<body","<body style='width:"+(parseInt(localStorage.pageWidth)-20)+"px' ").replace(/<a href=(['"])(#.*?)/ig,'<a skip="" href=$1$2').replace(/<a href=(['"])/ig,'<a onclick="return goAnotherPage(event)" href="#" title=$1')+'<script>$(document).trigger("DOMContentLoaded")<\/script>';background.wikicache[a]=d;document.open();document.write(d);document.close();modifyPageAfterLoad()}}};c.send()}}
function modifyPageAfterLoad(){document.onmouseup=function(a){createRightClickPopupBox(a)};if(localStorage.fontSize)document.getElementsByTagName("html")[0].style.fontSize=localStorage.fontSize+"em";else document.getElementsByTagName("html")[0].style.fontSize="0.8em"}var selectedText="";
function createRightClickPopupBox(a){if(b=document.getElementById("rightClickPopupBox"))b.parentNode.removeChild(b);if(a.button==2){selectedText=window.getSelection().toString();if(selectedText!=""){var b=document.createElement("div");b.setAttribute("style","position: absolute; cursor: pointer; background-color: white; -webkit-box-shadow: 1px 1px 7px black;top: "+(a.y+window.pageYOffset)+"px; left: "+a.x+"px;");b.id="rightClickPopupBox";b.innerHTML='<div id="rightClickPopupBoxSearch" style="margin: 5px">Search for "'+
selectedText.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")+'"</div>';document.getElementsByTagName("body")[0].appendChild(b);if(parseInt(b.style.left)+b.clientWidth>=document.width)b.style.left=parseInt(b.style.left)-b.clientWidth+"px";document.getElementById("rightClickPopupBoxSearch").onmouseover=function(){document.getElementById("rightClickPopupBox").style.backgroundColor="#ffb"};document.getElementById("rightClickPopupBoxSearch").onmouseout=function(){document.getElementById("rightClickPopupBox").style.backgroundColor=
"white"};document.getElementById("rightClickPopupBoxSearch").onmouseup=function(c){if(selectedText!=""){c.preventDefault();c.stopPropagation();parent.document.getElementById("searchbox").value=selectedText;parent.doSearch();document.getElementById("rightClickPopupBox").parentNode.removeChild(b)}}}}}
function goAnotherPage(a){console.log(a);if(a.currentTarget.title.indexOf("http://")==0||a.currentTarget.title.indexOf("https://")==0)window.open(a.currentTarget.title,"_blank");else{var b=a.currentTarget.title;if(a.button==1)window.open("http://"+background.getCurrentLang()+".wikipedia.org"+b,"_blank");else{b=b.replace(/^(\/zh.*?\/)/i,"/wiki/");background.handleLink(decodeURIComponent(b))}}return false};
