var background=chrome.extension.getBackgroundPage(),VERSION=1.7;function welcome_init(){if(!localStorage.welcomeshown&&!localStorage.updateread){document.getElementById("welcome").innerHTML="<div style='height: 13px;'></div>"+chrome.i18n.getMessage("welcomeMessage")+" - <b>Click here to begin!</b>";document.getElementById("welcome").style.display="block"}}
function welcome_dismiss(){localStorage.setItem("welcomeshown","true");localStorage.setItem("updateread",VERSION);window.open("http://blog.visibotech.com/2010/09/thank-you-for-installing-wikipedia.html");window.close()}function update_init(){if(localStorage.welcomeshown)if(!localStorage.updateread||localStorage.updateread<VERSION){document.getElementById("update").innerHTML=chrome.i18n.getMessage("updateMessage",[VERSION]);document.body.setAttribute("updated","true")}}
function update_dismiss(){localStorage.welcomeshown=true;localStorage.updateread=VERSION;window.open("http://blog.visibotech.com/search/label/WikipediaCompanion");window.close()}
function init(){welcome_init();update_init();document.getElementById("clearhistorybutton").title=chrome.i18n.getMessage("clearHistory");document.getElementById("backbutton").title=chrome.i18n.getMessage("goBack");document.getElementById("forwardbutton").title=chrome.i18n.getMessage("goForward");document.getElementById("searchbutton").title=chrome.i18n.getMessage("search");document.getElementById("language").innerHTML=chrome.i18n.getMessage("language");document.getElementById("openInTab").innerHTML=
chrome.i18n.getMessage("openInTab");document.getElementById("options").innerHTML=chrome.i18n.getMessage("options");resizePage();checkForRefresh();document.getElementById("searchbox").focus();checkLang();updateButtonState()}function resizePage(){document.body.style.width=localStorage.pageWidth;document.getElementById("wikipage").style.width=localStorage.pageWidth}
function checkForRefresh(){if(localStorage.refresh)if(localStorage.refresh=="true"){document.getElementById("wikipage").src="./content.html";localStorage.refresh="false"}setTimeout(function(){checkForRefresh()},100);updateButtonState()}function doSearch(){var a=document.getElementById("searchbox");background.handleLink("/wiki/"+a.value);updateButtonState()}
function moveInHistory(a){if(!(background.currentHistoryPosition+a<0))if(!(background.currentHistoryPosition+a>=background.wikihistory.length)){background.currentHistoryPosition+=a;localStorage.refresh="true";updateButtonState()}}function clearHistory(){background.wikihistory=[];background.wikicache={};background.currentHistoryPosition=0;updateButtonState()}function openInNewTab(){var a=getRegularWikiURL();if(a!=false){window.open(a,"_blank");window.close()}}
function openOptions(){window.open("options.html");window.close()}function getRegularWikiURL(){if(background.wikihistory[background.currentHistoryPosition]==null)return false;var a=background.wikihistory[background.currentHistoryPosition].url;try{return a=wikipage.document.querySelector(".searchresults")?a.replace(".m.wikipedia.org/wiki/",".wikipedia.org/w/index.php?title=Special:Search&search="):a.replace(".m.wikipedia.org",".wikipedia.org")}catch(c){return false}}
function getCurrentWikiPageLang(){if(background.wikihistory[background.currentHistoryPosition]==null)return"";return background.wikihistory[background.currentHistoryPosition].lang}function getCurrentWikiPageTitle(){if(background.wikihistory[background.currentHistoryPosition]==null)return"";return background.wikihistory[background.currentHistoryPosition].title}
function toggleLang(){background.toggleLang();if(background.checkLang().state==0){document.getElementById("primaryLang").style.fontWeight="bold";document.getElementById("secondaryLang").style.fontWeight=""}else{document.getElementById("primaryLang").style.fontWeight="";document.getElementById("secondaryLang").style.fontWeight="bold"}loadLangURL()}
function checkLang(){var a=background.checkLang(),c=document.getElementById("language");if(a.secondaryLang){c.style.display="";c.innerHTML="<span id='primaryLang'>"+a.primaryLang+"</span> | <span id='secondaryLang'>"+a.secondaryLang+"</span>";if(a.state==0){document.getElementById("primaryLang").style.fontWeight="bold";document.getElementById("secondaryLang").style.fontWeight=""}else{document.getElementById("primaryLang").style.fontWeight="";document.getElementById("secondaryLang").style.fontWeight=
"bold"}}else c.style.display="none"}function updateButtonState(){document.getElementById("clearhistorybutton").setAttribute("disabled",background.wikihistory.length<=1);document.getElementById("backbutton").setAttribute("disabled",background.currentHistoryPosition>=background.wikihistory.length-1);document.getElementById("forwardbutton").setAttribute("disabled",background.currentHistoryPosition<=0)}
function loadLangURL(){document.getElementById("wikipage").src="./loading.html";var a=background.getCurrentLang(),c=getRegularWikiURL();if(c==false)localStorage.refresh="true";else{var d=new XMLHttpRequest;d.open("GET",c,true);d.onreadystatechange=function(){if(d.readyState==4){var b=d.responseText;if(b!=""){b=RegExp('<li class="interwiki-'+a+'"><a href="http.+wikipedia.org(.+)">',"gi").exec(b);if(b!=null&&b.length>1)background.handleLink(b[1]);else{console.log("No wikipedia page in this language...");
if(background.wikihistory[background.currentHistoryPosition]!=null){b=background.wikihistory[background.currentHistoryPosition].url.replace(/^.+(\/wiki\/.+)/,"$1");console.log(b);background.handleLink(b)}}}}};d.send()}};
