--- ./modules/overlay-plane/Makefile.ORIG	Tue Nov 26 16:40:31 2002
+++ ./modules/overlay-plane/Makefile	Tue Nov 26 16:40:59 2002
@@ -404,13 +404,13 @@
 
 
 %.x %.doc: %.c
-	$(SCWM_SRC_DIR)/scwm-snarf $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).x && \
+	$(SCWM_SRC_DIR)/scwm-snarf $< $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) > $(basename $<).x && \
 	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).doc \
 	|| { rm $(basename $<).x $(basename $<).doc ; false; }
 
 %.x %.doc: %.cc
 	CC=$(CXX) \
-	$(SCWM_SRC_DIR)/scwm-snarf -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).x && \
+	$(SCWM_SRC_DIR)/scwm-snarf $< -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) > $(basename $<).x && \
 	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).doc \
 	|| { rm $(basename $<).x $(basename $<).doc ; false; }
 
