#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

: ${yopp_p=}

while (($# > 0))
do
  case "$1" in 
      --yopp|-y) yopp_p=t;;
      --) shift; break;;
      *) break;;
  esac
  shift
done

ap=$(me-expand-dest ap)
vsetp "${ap}" || {
    echo "Can't find ap dir."
    exit 1
} 1>&2

apbin="${ap}/bin"
[ -d "${apbin}" ] || {
    echo "${apbin} isn't."
    exit 1
} 1>&2

apbinmake="${apbin}/make"
[ -x "${apbinmake}" ] || {
    echo "${apbinmake} isn't."
    exit 1
} 1>&2

EExec_verbose_msg "making in PWD>$PWD<"
EExec "${apbinmake}" "$@"
vtruep "${yopp_p}" && EExec email-yopp apmake: \""${apbinmake}" "$@"\" is done.
