#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

ap=$(me-expand-dest ap)
vsetp "${ap}" || {
    echo "Can't find ap dir."
    exit 1
} 1>&2

apbin="${ap}/bin"
[ -d "${apbin}" ] || {
    echo "${apbin} isn't."
    exit 1
} 1>&2

apbinmake="${apbin}/make"
[ -x "${apbinmake}" ] || {
    echo "${apbinmake} isn't."
    exit 1
} 1>&2

EExec "${apbinmake}" "$@"
