#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
EExec_verbose_msg $(echo_id eexec_program)
unset eexec_program

cd_p=
bin_parent=$(me-expand-dest TOT)
bin_dir="./bin/"

while (($# > 0))
do
  case "$1" in
      --cd|--go|--there) cd_p=t;;
      --stay|--here|-.|--.|--dot) cd_p=;;
      --no-bin) bin_dir=;;
      --) shift; break;;
      *) break;;
  esac
  shift
done


bin_path="${bin_parent}/${bin_dir}"
[ -e "${bin_path}/TOT" ] && {
    echo "TOT not in this dir. Run this some other way. I'll add an override later."
    exit 1
}

if vsetp "${cd_p}"
then
    EExec cd "${bin_parent}"
    EExec "${bin_dir}""$@"
else
    EExec "${bin_path}""$@"
fi
