#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
EExec_verbose_msg $(echo_id eexec_program)
unset eexec_program

cd_p=
ap=$(me-expand-dest ap)
bin_dir="./bin/"

while (($# > 0))
do
  case "$1" in
      --cd|--go|--there) cd_p=t;;
      --stay|--here|-.|--.|--dot) cd_p=;;
      --no-bin) bin_dir=;;
      --) shift; break;;
      *) break;;
  esac
  shift
done

if vsetp "${cd_p}"
then
    EExec cd "${ap}"
    EExec "${bin_dir}""$@"
else
    EExec "${ap}${bin_dir}""$@"
fi
