#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
EExec_verbose_msg $(echo_id eexec_program)
unset eexec_program

while (($# > 0))
do
  case "$1" in
      --cd) EExec cd $(depth);;
      --) shift; break;;
      *) break;;
  esac
  shift
done
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

EExec $(depth)/bin/"$@"
