#!/bin/sh
#
# Revert the files changed by a `received' as2 bundle.
# Applicable output:
#e.g. Bundle status: completed
#e.g. Bundle A814217 by weix@weix_t124_tree_1_hw_hk queued on 2013/01/22 23:55:18

#e.g. 		   Updated for bug 1221397. Initial version for EngCpu.	

#e.g. Affected files ...
#e.g. <blank-line>
#e.g. ... //hw/ap/drv/multiengine/Makefile#26 edit
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu.h#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_imp.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_imp.h#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_scheduler.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_scheduler.h#1 add
#e.g. ... //hw/ap/drv/multiengine/framework/cfgparser/cfg_parser.cpp#27 edit
#e.g. ... //hw/ap/drv/multiengine/framework/cfgparser/cfg_parser_cpu.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/framework/cfgparser/cfg_parser_cpu.h#1 add
#e.g. ... //hw/ap/drv/multiengine/framework/misc.h#76 edit
#e.g. ... //hw/ap/drv/multiengine/multiengine.mk#15 edit
#e.g. <blank-line>
#e.g. Differences ...


source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

# Get the files that were affected.
[ -z "$*" ] && {
    echo "No bundle ids specified."
    exit 1
} 1>&2

[ "${1}" = '--help' ] && {
    echo "as2-revert bundle-id...
Revert files changed by the bundle.
"
    exit 0
}

for bundle_id in "$@"
do
  files=$(dpas2-list-bundle-files "${bundle_id}")
  while :
    do
    echo_id files
    echo
    read -e -p "p4 revert these files from bundle_id>${bundle_id}< [N/y/q]? "
    case "$REPLY" in
        [Yy]) revert_p=t; break;;
        [Nn]) revert_p=; break;;
        [Qq]) exit 0;;
        *) continue;;
    esac
  done
  if [ -n "${revert_p}" ]
  then
      EExec p4 revert "$files"
  else
      echo "Skipping revert of bundle>${bundle_id}<"
  fi
  echo
done

