#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
EExec_verbose_msg $(echo_id eexec_program)
unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

: ${build_framework_p=t}
: ${build_plugins_p=}

while (($# > 0))
do
  case "$1" in
    --debug) check_debug_p=t;;
    --build-framework|--build-fw|--framework|--fw) build_framework_p=t;;
    --no-build-framework|--no-build-fw|--no-framework|--no-fw) build_framework_p=;;
    --build-plugins|--plugins) build_plugins_p=t;;
    --no-build-plugins|--no-plugins) build_plugins_p=;;
    --) shift; break;;
    *) break;;
  esac
  shift
done

true_p "${build_framework_p}" && {
    NV_MTE_DEVELOPMENT=1 EExec bin/t_make -only t210_gpu_multiengine-framework
}

true_p "${build_plugins_p}" && {
    NV_MTE_DEVELOPMENT=1 EExec bin/t_make -only t210_gpu_multiengine-plugins
}
