#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

#cd `depth`
#make -j4 NV_GENERATE_MODS=build MODS_RUNSPACE=/home/scratch.jsmith_fermi/jsmith_fermi1_gf100_tree1/hw/nvdiag/mods \
#  MODS_SW_TREE_PATH=dev/gpu_drv/chips_a  genmods

my_modsdir=$(me-expand-dest mods)
echo_id my_modsdir
mecd tot
echo "pwd: $(pwd)"
EExec bin/make -j4 \
    NV_GENERATE_MODS=build \
    MODS_RUNSPACE="${my_modsdir}" \
    MODS_SW_TREE_PATH=dev/gpu_drv/chips_a \
    genmods

