#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${use_gui_p=t}

# as2 describe prefixes modified files with "... "
# "." is a wildcard.
export prefix="[.][.][.] "

for bundle in "$@"
do
  echo_id bundle
  files_to_revert=$(as2 describe "${bundle}" | dp4-extract-pathname)
  vunsetp "${files_to_revert}" && {
      echo "No files to revert in bundle ${bundle}."
      continue
  } 1>&2

  vsetp "${use_gui_p}" && {
      files_to_revert=$(echo ${files_to_revert} | xlist)
      vunsetp "${files_to_revert}" && {
          echo "No files to revert were selected from bundle ${bundle}."
          continue
      } 1>&2
  }
  echo "files to revert: ${files_to_revert}"
  ans=
  while vunsetp "${ans}"
  do
    read -e -p "Revert? "
    case "${REPLY}" in
        [Yy1t]) ans=y;;
        [Nn0f]) ans=n;;
        *) continue;;
    esac
  done

  [ "${ans}" = 'n' ] && continue

  echo EExec p4 revert "${files_to_revert}"
done

