#!/bin/sh
#
# Revert the files changed by a `received' as2 bundle.
# Applicable output:
#e.g. Bundle status: completed
#e.g. Bundle A814217 by weix@weix_t124_tree_1_hw_hk queued on 2013/01/22 23:55:18

#e.g. 		   Updated for bug 1221397. Initial version for EngCpu.	

#e.g. Affected files ...
#e.g. <blank-line>
#e.g. ... //hw/ap/drv/multiengine/Makefile#26 edit
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu.h#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_imp.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_imp.h#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_scheduler.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/drvapi/cpu/eng_cpu_scheduler.h#1 add
#e.g. ... //hw/ap/drv/multiengine/framework/cfgparser/cfg_parser.cpp#27 edit
#e.g. ... //hw/ap/drv/multiengine/framework/cfgparser/cfg_parser_cpu.cpp#1 add
#e.g. ... //hw/ap/drv/multiengine/framework/cfgparser/cfg_parser_cpu.h#1 add
#e.g. ... //hw/ap/drv/multiengine/framework/misc.h#76 edit
#e.g. ... //hw/ap/drv/multiengine/multiengine.mk#15 edit
#e.g. <blank-line>
#e.g. Differences ...

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${use_gui_p=t}

# as2 describe prefixes modified files with "... "
# "." is a wildcard.
export prefix="[.][.][.] "

for bundle in "$@"
do
  echo_id bundle
  ### all files are on one line. files_to_revert=$(dpas2_list_bundle_files "${bundle}")
  files_to_revert=$(as2 describe "${bundle}" | dp4-extract-pathname)
  vunsetp "${files_to_revert}" && {
      echo "No files to revert in bundle ${bundle}."
      continue
  } 1>&2

  for f in ${files_to_revert} 
  do
    echo "${f}"
  done | dp4-revert-selected
done

