#!/bin/sh

source script-x
source eexec
set -u
progname="$(basename $0)"

eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

on-o-xterm-p && {
    echo "$progname: Should not do this on an o-xterm box."
    exit 1
} 1>&2

: ${debug_p="-debug"}
: ${purge_p="t"}
: ${clean_p="t"}
: ${make_type=mmake}
: ${build_program:="./build_gpu_multiengine.pl"}

case "$make_type" in
    mmake) EExec mmake "$@";;
    t_make) EExec t_make+log.sh "$@";;
    make) EExec make "$@";;
    *) ;;                       # Just want the tests to be built.
}

banner "Build tests?"
read -e -p "[Yy] -- default: Build tests w/debug.
d -- Build tests w/NO debug
n -- Don't build tests.
? "

continue=y
while [ -n "${continue}" ]
do
  continue=
  case "$REPLY" in
      [Nn0f]|nil) exit 0;;
      [Dd]) debug_p=;;
      ""|[yY1t]) debug_p="-debug";;
      *) echo "Unsupported option, try again." 1>&2
         continue=t
         ;;
  esac
done

EExec -y cd $(me-dogo testgen)

[ -e "${build_program}" ] || {
    echo "$PWD: build_program>$build_program< does not exist."
    exit 1
} 1>&2

[ -x "${build_program}" ] || {
    echo "$PWD:build_program>${build_program}< is not executable."
    exit 1
} 1>&2

[ -n "${clean_p}" ] && {
    EExec "${build_program}" clean
}

[ -n "${purge_p}" ] && {
    EExec "${build_program}" purge
}

EExec "${build_program}" ${debug_p}

