#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

patterns=("^LD" 
"(Info|Warning): \[ nvclk=(-1|0) "
"Warning: \[ nvclk=.*PFIFO Reset being triggered,"
"Warning: .*does not have PCI bus!"
"WARNING: This log print has triggered"

"^[* #]*$"
"WARNING[[:space:]]+WARNING"
"ENGINEERING MODS RELEASE"
"Not for use outside NVIDIA"
"Warning: Unable to open sim.txt, creating a new one"
"is already registered"
"^WARNING! RAMFC offset 0x64 is missing from the channel switcher table"
"^Warning:.*has no (producer|consumer)"
"^WARNING: [3943] Pinmux sequence not present, limited functionality available"
"Warning: Disabling ELPG due to context switch being disabled!"
"argument ' ' not used!"
)

pattern=$(add-to-var.py  -s '|' pattern "${patterns[@]}")

#echo_id pattern

egrep -v -e "${pattern}"
