#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${just_print_p=}

regexps=()
# Who knows when or where this can happen
# Error opening surface_write_read.so: /lib/tls/libc.so.6: version `GLIBC_2.4' not found
regexps+=("Error opening.*\.so:.*lib.*not found")

# ASIM bullshit
# ERROR: cannot aquire /tmp/asim.X
regexps+=("ERROR: cannot aquire /tmp/asim.X")

# RTL bullshit
# something bad happened
# Yes, that's the message. something. bad. happened.
regexps+=("something bad happened")

[ "${1-}" = "-p" ] && {
    shift
    settrue just_print_p
}

regexp=
sep=

{
    EExec_verbose_msg "Looking for these test killing regexps:"
    for r in "${regexps[@]}"
    do
      EExec_verbose_msg " >${r}<"
      regexp="${regexp}${sep}${r}"
      sep="|"
    done
} 1>&2

vtruep "${just_print_p}" && {
    echo "${regexp}"
    exit 0
}

EExecDashV_p && echo_id 1>&2 regexp

egrep "${regexp}" "$@"
