#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
EExec_verbose_msg $(echo_id eexec_program)
unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

all_chips="t124
t132
t210"

: ${chip_list=${all_chips}}
: ${tree_dot_make=$(me-expand-dest tot)/tree.make}
: ${check_debug_p=}


while (($# > 0))
do
  case "$1" in
    --debug) check_debug_p=t;;
    --) shift; break;;
    *) break;;
  esac
  shift
done

debug_chip=
chip=
done_p=
for tmp_chip in ${chip_list}
do
  vtruep "${check_debug_p}" && {
      egrep -q "^[[:space:]]*export[[:space:]]+(NV_)?PROJECTS?.*${tmp_chip}_debug" "${tree_dot_make}" && {
          debug_chip="${tmp_chip}_debug"
          done=t
      }
  }
  egrep -q "^[[:space:]]*export[[:space:]]+(NV_)?PROJECTS?.*${tmp_chip}([^_]|$)" "${tree_dot_make}"  && {
      chip="${tmp_chip}"
      done_p=t
  }

  vtruep "${done_p}" && {
      vsetp "${chip}" && echo "${chip}"
      vsetp "${debug_chip}" && echo "${debug_chip}"
      exit 0
  }
done

echo 1>&2 "Cannot determine chip."
exit 1
