#!/bin/sh

source script-x
progname="$(basename $0)"
source eexec
set -u

eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${ap_dir:=}
: ${p4_root=${1-"."}}
: ${send_mail_on_completion:=t}

[ -z "$ap_dir" ] && {
    ap_dir=$(find-ap-dir)
}

[ -d "${ap_dir}" ] || {
    echo "ap_dir>${ap_dir}<, isn't."
    exit 1
} 1>&2

ap_dir=$(basename "${ap_dir}")

# For T124/132 work, you want 
# //arch/traces/mobile/traces/gpu_multiengine/sanity_gr_disp_syncpt
# //hw/ap_tlit1/inf/mods/trace_3d/plugin/1.0/src/t3dplugin.cpp



#
# Original suggested minimal set of files to index for MultiEngine Testing..
# //hw/${ap_dir}/drv/drvapi
# //hw/${ap_dir}/drv/multiengine
# //arch/traces/mobile/traces/gpu_multiengine/
# //arch/traces/mobile/traces/nongpu_multiengine/
# //hw/${ap_dir}/inf/mods/trace_3d/plugin/
#
# /home/scratch.dpanariti_t124/t124_0/arch/traces/mobile/traces/gpu_multiengine/sanity_bsea/sanity_bsea.cpp

####
## Let's see if all of drv chokes us or not... YES.
## //hw/${ap_dir}/drv/drvapi
## //hw/${ap_dir}/drv/multiengine
####
base_depot_dirs_of_interest="
//hw/${ap_dir}/drv/drvapi/
//hw/${ap_dir}/drv/multiengine/
//hw/${ap_dir}/inf/mods/trace_3d/plugin/
//arch/traces/mobile/traces/gpu_multiengine/
//arch/traces/mobile/traces/nongpu_multiengine/
"

# too big: //hw/${ap_dir}/include/
# Taken care of with NOTAG files.
# I would like the contents of the dir itself, however. Need to add files by hand.
# /home/scratch.dpanariti_t124_1/t124_1/hw/${ap_dir}/drv/simfront/Main.cpp
# !&@^%#&^@%#! //hw/${ap_dir}/include/ works if it is in this order.
# order dependence sucks.

# Adding //hw/${ap_dir}/clib causes (error Rerun etags...) problems.
more_depot_dirs_of_interest="
//hw/${ap_dir}/include
//hw/${ap_dir}/ip/vdec/cmod/
//hw/${ap_dir}/drv/simfront/
//hw/${ap_dir}/drv/bootrom/
//hw/${ap_dir}/drv/chiplib/
//hw/${ap_dir}/clib/
//hw/class/
//hw/tools/mods
//hw/tools/shimlib/
//hw/kepler1_gklit3/clib/
//hw/kepler1_gklit3/diag/"

depot_dirs_of_interest="$base_depot_dirs_of_interest $more_depot_dirs_of_interest"

dirs_of_interest=$(dp4-reroot "$p4_root" $depot_dirs_of_interest)

[ -z "${skip_cd-}" ] && EExec -y mecd sandbox
echo "cwd: $(pwd)"

EExec -y index-code $EExecDashN_opt $EExecDashV_opt $dirs_of_interest

vsetp "${send_mail_on_completion-}" && ! EExecDashN_p && {
    mail -s "$progname is done in ${PWD}." "${USER}" < /dev/null >/dev/null 2>&1
}
