#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
#unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
export eexec_program

: ${oot_only_p=}
# These are me-expand'd
# Additional ap type dirs will need to be -a'd.
source $HOME/.rc/env.nvidia
: ${db_locs=${DP_NV_ME_DB_LOCS=ap //arch //sw/dev //sw/mods //sw/tools //hw/class //hw/kepler1_gklit3 //hw/tools}}
: ${db_loc_excludes=}

#WTF? nvcscope_filter()
#WTF? {
#WTF?     egrep -v '/ap(_tlit[0-9]/'
#WTF? }

no_filter()
{
    cat
}

filter_dirs()
{
    local re="$1"
    shift
    # Get one per line. I'm sure there're 10^6 better ways to do this. split/cut?
    for d in "$@"
    do
      echo "$d"
    done | egrep -v "$re"
}

OOT_DIR=$HOME/work/out-of-tree-dirs
# All must be absolute
out_of_tree_dirs=/home/scratch.traces02/mobile/traces/system/so
index_out_of_tree_locations()
{
    local oot_files_file=$(normpath "${OOT_DIR}/oot.files")
    EExec find-src-code-files ${out_of_tree_dirs} > "${oot_files_file}"
    # Places like home.scratch.traces02.mobile.traces.system.so which do
    # not reside in a checked out tree. I don't know
    # how/when/why/where/from where these come, but there they are.
    # Apparently they are ~needed to make it go~.
    (
        # gtags can really be a PITA sometimes.
        EExec cd /
        EExec gtags -f "${oot_files_file}" "${OOT_DIR}"

        EExec cd "${OOT_DIR}"
        EExec cscope -q -b -i "${oot_files_file}"
    )
}

: ${ap_dir:=}
: ${send_mail_on_completion:=t}
# Existence of different dirs is one thing, but different names for the same
# fooking dirs is fooking stoopid. So I can't use it. What a crock.
: ${nvcscope_p=}
# At the least, just_nvcscope_p prevents me needing to know the nvcscope
# option name to make symlinks.
: ${just_nvcscope_p=}
: ${nvcscope_files=cscope.files cscope.out cscope.out.in cscope.out.po}
: ${skip_cd_p=}
: ${follow_links_arg=}
: ${follow_links_on_command_line=t}
: ${cron_opt=}

link_or_non_existent()
{
    local file="${1}"
    shift

    ! [ -e "${file}" ] || [ -L "${file}" ]
}

# Usage variable usage:
Usage_args_info=""
Usage_synopsis="Index some useful, hard coded source dirs
Use the nvcscope ap index by default.
"
# Using ) after the args makes copy & paste between here and the 
# case statement easier.
Usage_details="${EExec_parse_usage}
-m|--no-nvcscope|--old-sk00l) Mundane usage, just index all dirs into sandbox
                              root just like the old days.
--nvcscope|--new-sk00l) Use nvcscope's db for ap tree. Currently problematical
                        because GTAGS can only use one db, so the non-ap GTAGS
                        needs *all*files.
-j|--no-me-index|--no-arch-index|--no-other-index) Just set up nvcscope.
-oot) Index out of tree files only.
"
# Example of arg parsing.
option_str="${EExec_parse_option_str}jmhHe:a:i:"
long_options=(
"mundane" "no-nvcscope"
"no-me-index" "no-arch-index" "just-nvcscope" "links" "just-links"
"skip-cd" "stay-put" "oot" "cron"
"exclude-db-loc:"
"add-db-loc:"
"init-db-loc:")
source dp-getopt+.sh
for i in "$@"
do
  # do. e.g.  shift; $OPTION_ARG=$1;; # to process options with arguments.
  case $1 in
      # Program options.

      -m|--no-nvcscope|--mundane) nvcscope_p=;;
      --nvcscope|--new-sk00l) nvcscope_p=t;;
      -j|--no-me-index|--no-arch-index|--no-other-index|--links|--just-links) just_nvcscope_p=t;;
      -h) follow_links_arg=-h;;
      -H) follow_links_arg=;;
      --skip-cd|--stay-put) skip_cd_p=t;;
      --oot) oot_only_p=t; nvcscope_p=; just_nvcscope_p=;;
      --cron) cron_opt="--cron";;
      -e|--exclude-db-loc) shift; db_loc_excludes="${db_loc_excludes} ${1}";;
      -a|--add-db-loc) shift; db_locs="${db_locs} ${1}";;
      -i|--init-db-loc) shift; db_locs="${1}";;
      # Help!
      --help) Usage; exit 0;;
      --) shift ; break ;;
      *) dp_echo2 "Unsupported option>$1<"
         exit 1;;
    esac
    shift
done

if true_p "${oot_only_p}"
then
    index_out_of_tree_locations
    dp_echo "Indexing oot only. Exiting."
    exit
fi

[ -z "$ap_dir" ] && {
    ap_dir=$(find-ap-dir) || {
        echo "Cannot find ap dir."
        exit 1
    } 1>&2
}

[ -d "${ap_dir}" ] || {
    dp_echo "ap_dir>${ap_dir}<, isn't."
    exit 1
} 1>&2

vsetp "${skip_cd_p}" || EExec -y mecd sandbox
dp_echo2 "cwd: $(pwd)"

ap_path="${ap_dir}"
ap_dir=$(basename "${ap_dir}")
: ${p4_root=${1-"."}}
p4_root=$(realpath "${p4_root}")

true_p "${just_nvcscope_p}" && {
    nvcscope_p=t
}

ap_hw_p4_path="//hw/${ap_dir}"
ap_gpu_me_inf="//hw/ap/ip/inf/gpu_multiengine/1.0"

# For T124/132 work, you want
# //arch/traces/mobile/traces/gpu_multiengine/sanity_gr_disp_syncpt
# //hw/ap_tlit1/inf/mods/trace_3d/plugin/1.0/src/t3dplugin.cpp

#
# Original suggested minimal set of files to index for MultiEngine Testing..
# //hw/${ap_dir}/drv/drvapi
# //hw/${ap_dir}/drv/multiengine
# //arch/traces/mobile/traces/gpu_multiengine/
# //arch/traces/mobile/traces/nongpu_multiengine/
# //hw/${ap_dir}/inf/mods/trace_3d/plugin/
#
# /home/scratch.dpanariti_t124/t124_0/arch/traces/mobile/traces/gpu_multiengine/sanity_bsea/sanity_bsea.cpp

pre_t210_gpu_me_tests="
//arch/traces/mobile/traces/gpu_multiengine/
//arch/traces/mobile/traces/nongpu_multiengine/"

t210_gpu_me_tests="
${ap_gpu_me_inf}/clib/gpu_multiengine"

chip=$(guess-chip)
EExec_verbose_msg "guessed $(echo_id chip)"
case "${chip}" in
    t210) gpu_me_tests="${t210_gpu_me_tests}";;
    t124|t132) gpu_me_tests="${pre_t210_gpu_me_tests}";;
    *) echo 1>&2 "Unknown chip>${chip}<, exiting."; exit 1;;
esac

#
# New layout:
# //hw/ap/ip/inf/gpu_multiengine/1.0/clib/gpu_multiengine
#
### Files out of source tree when using /home/scratch.traces02/mobile/traces/system/so/
### Tried to do it at root, but it makes things relative to root, e.g. /home/x --> home/x
base_depot_dirs_of_interest="
${ap_hw_p4_path}/drv/drvapi/
${ap_hw_p4_path}/drv/multiengine/
${ap_hw_p4_path}/inf/mods/trace_3d/plugin/
${gpu_me_tests}
//hw/kepler1_gklit3/manuals/"

# too big: //hw/${ap_dir}/include/
# Taken care of with NOTAG files.
# I would like the contents of the dir itself, however. Need to add files by hand.
# /home/scratch.dpanariti_t124_1/t124_1/hw/${ap_dir}/drv/simfront/Main.cpp
# !&@^%#&^@%#! //hw/${ap_dir}/include/ works if it is in this order.
# order dependence sucks.

# Adding //hw/${ap_dir}/clib causes (error Rerun etags...) problems.
more_depot_dirs_of_interest="
${ap_hw_p4_path}/include/
${ap_hw_p4_path}/ip/vdec/cmod/
${ap_hw_p4_path}/drv/simfront/
${ap_hw_p4_path}/drv/bootrom/
${ap_hw_p4_path}/drv/chiplib/
${ap_hw_p4_path}/clib/
//hw/class/
//hw/oot/
//hw/tools/mods
//hw/tools/shimlib/
//hw/kepler1_gklit3/clib/
//hw/kepler1_gklit3/diag/
//dev/cpu/tools/sim/asim/1.0/"

sw_depot_dirs_of_interest="
//sw/dev/
//sw/mods/
//sw/tools/"

depot_dirs_of_interest="${base_depot_dirs_of_interest} ${more_depot_dirs_of_interest} ${sw_depot_dirs_of_interest}"

other_dirs_of_interest=""

echo_id2 ap_dir
echo_id2 ap_path
echo_id2 ap_hw_p4_path
echo_id2 p4_root

dirs_of_interest=$(dp4-reroot "$p4_root" $depot_dirs_of_interest)
dirs_of_interest="${dirs_of_interest} ${other_dirs_of_interest}"
echo_id2 dirs_of_interest


# These files change and come and go and are mostly copies of existing files.
# This kind of stuff confuses cscope.
# Sadly, my code indexing system is soooo convoluted that this is the only
# way to control the source code finder from here.
export EXCLUDE_PAT="/plex/"

if true_p "${nvcscope_p}"
then
    # St00p1d god damn mother f00ck1ng b00llsh1t a55hole 1d1ocy!
    # One tree:
    # //hw/ap_tlit1/drv/multiengine/framework/utils/loader/stream_loader.cpp
    # Another:
    # //hw/ap_tlit1/drv/multiengine/framework/utilities/loader/stream_loader.cpp
    # H0w can any thing be s0 fncking stnpid?
    ap_hw_path=$(dp4-reroot "$p4_root" "${ap_hw_p4_path}")
    #echo_id2 ap_hw_p4_path
    #echo_id2 ap_hw_path
    #echo_id2 dirs_of_interest
    # Filter out dirs here so we don't even look inside them.
    # Remove the ap tree since nvcscope already handles it.
    dirs_of_interest=$(filter_dirs "${ap_hw_path}" ${dirs_of_interest})
    #echo_id2 dirs_of_interest
    (
        link_em=t
        cd "${ap_path}"
        for cscope_file in ${nvcscope_files}
        do
          link_or_non_existent "${cscope_file}" || {
              link_em=
              dp_echo2 "$cscope_file exists and is not a link."
              break;
          }
        done
        if true_p "${link_em}"
        then
            EExec rm -f ${nvcscope_files}
            EExec nvcscope --link-this-tree-to-prebuilt-indexes
        else
            dp_echo2 "Not linking nvcscope files because of errors."
        fi
    )
fi

# Make sure we can match whole words by ensuring " "s for delimiters.
db_locs=" ${db_locs} "
for exclude in ${db_loc_excludes}
do
  db_locs=$(echo "${db_locs}" | sed -r "s! $exclude !!")
done
echo_id2 db_locs
#exit 99

if ! true_p "${just_nvcscope_p}"
then
    all_indexed=
    all_db_locs=
    for db_loc in ${db_locs}
    do
      index_dirs=
      #echo_id2 db_loc
      #db_loc=$(dp4-reroot . "${db_loc}")
      db_loc=$(me-expand-dest "${db_loc}")
      #echo_id2 db_loc
      [ -d "${db_loc}" ] || continue
      for doi in ${dirs_of_interest}
      do
#         echo_id2 doi
#         echo_id2 db_loc
        # Select the dirs of interest under this db_loc
        case "${doi}/" in
            $db_loc/*) index_dirs="${index_dirs}
${doi}";;
            *) ;; #echo "no match>$doi<";;
        esac
      done
      vunsetp "${index_dirs}" && {
          dp_echo2 "*** No dirs for db_loc>$db_loc< ***"
          continue
      }
#       echo_id2 db_loc
#       echo_id2 index_dirs
      all_indexed="${all_indexed}
>${index_dirs}<"
      cd "${db_loc}"
      echo_id2 PWD
      EExec index-code $follow_links_arg $index_dirs
      all_db_locs="${all_db_locs} ${db_loc}"
    done
    echo_id2 dirs_of_interest
    echo_id2 all_indexed
    echo_id2 all_db_locs

    index_out_of_tree_locations
else
    dp_echo "Not indexing non-nvcscope code."
fi

vsetp "${send_mail_on_completion-}" && {
    EExec email-yopp ${cron_opt}
}
