#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
#unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
export eexec_program

args=
while (($# > 0))
do
  case "$1" in
      --) shift; break;;
      -*) args="${args} ${1}";;
      *) break;;
  esac
  shift
done

# No sb1 no more.
vunsetp "$*" && {
    set -- $sb4 $sb3 $sb2 $sb5
}

for sb in "$@"
do
  (EExec -y cd "${sb}" && pwd && EExec nice index-me-code ${args}) &
done
wait
echo "Indexing done."
