#!/bin/sh

# Do a go relative to the current source tree.
source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${error_msg_opt=}
: ${error_msgs_p=t}

for i in "$@"
do
  case "$1" in
      -z|--silent|--no-error-message|--quiet-errors) error_msg_opt=--quiet-errors; error_msgs_p=;;
      *) break;;
  esac
done

#: ${sb=""}
#export go_here_first="$sb"
# DUMBASS PARAMETER to relative dogo. Sometimes I really bug myself.
export domain="__SB_rel"
relative_to=$(dp-sb-root) || {
    relative_to=$(depth)/../..
}
# XXX @todo STUPID way to pass parameters.
export relative_to              # DUMBASS PARAMETER to relative dogo
EExec_verbose_msg "cwd: $PWD"
EExec ${error_msg_opt} relative-dogo ${DP_SCRIPT_X_DEBUG_PROPAGATOR} "$@"
