#!/bin/sh

# Do a go relative to the current source tree.
source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

#: ${sb=""}
#export go_here_first="$sb"
export domain="__ME_src"
relative_to=$(dp4-sb-root) || {
    relative_to=$(depth)/../..
}
# XXX @todo STUPID way to pass parameters.
export relative_to
EExec relative-dogo "$@"

