#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

vsetp "${util_name-}" || {
    echo "The utility name needs to be passed in the \"util_name\" env var."
    exit 1
} 1>&2

binary=$(me-expand-dest "${util_name}")

exec "${binary}" "$@"

