#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${hold_mins:=${DP_HOLD_TREE_DEFAULT_MINS}}
: ${chown=}
: ${chown_opt=}

[ "${1-}" ] && {
    chown_opt=t
    shift
}

[ -n "$chown" ] && {
    chown_opt="-t"
}
    
[ -z "$*" ] && {
    echo -- ${DP_HELD_TREE_IDS-}
}

for tree_id in "$@"
do
  EExec_verbose_msg "Renewing hold on>$tree_id<"
  # -t says to change UID. This is *re*newing, so that should already have
  # been done.
  EExec as2 hold $chown_opt "${tree_id}" "${hold_mins}"
done
