#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${RTL_PRESENT_INDICATOR_FILE="DP_RTL_SB"}
: ${RTL_PRESENT_INDICATOR_FILE_SUFFIX=}
: ${RTL_PRESENT_INDICATOR_FILE_AUTO_SUFFIX="_AUTO"}
: ${build_dir=}
: ${make_it_p=}
: ${echo_name_p=}

for i in "$@"
do
  case "$1" in
      --name) echo_name_p=t;;
      -c|-t|--touch|--creat|--create) make_it_p=t;;
      -a|--auto) RTL_PRESENT_INDICATOR_FILE_SUFFIX="${RTL_PRESENT_INDICATOR_FILE_AUTO_SUFFIX}"; make_it_p=t;;
      --build-dir) shift; build_dir="${1}";;
      --here) build_dir=$PWD;;
      *) break;
  esac
  shift
done

sb=$(dp-sb-root -s)
#echo_id sb
#echo_id RTL_SANDBOXES
vsetp "${RTL_SANDBOXES-}" && {
    case "${RTL_SANDBOXES}" in
        :$sb:) exit 0;;
    esac
}

if vsetp "${build_dir}"
then
    cd "${build_dir}"
else
    mecd ap
fi

rtl_file=$(realpath "${RTL_PRESENT_INDICATOR_FILE}${RTL_PRESENT_INDICATOR_FILE_SUFFIX}")

true_p "${echo_name_p}" && {
true_p "${echo_name_p}" && {
    echo "${rtl_file}"
}

true_p "${make_it_p}" && {
true_p "${make_it_p}" && {
    EExec touch "${rtl_file}"
    exit 0
}

for f in ${RTL_PRESENT_INDICATOR_FILE}{,${RTL_PRESENT_INDICATOR_FILE_AUTO_SUFFIX}}
do
  [ -e "$f" ] && exit 0
done

exit 1   
