#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

RTL_PRESENT_INDICATOR_FILE="DP_RTL_SB"

[ "${1-}" = "--name" ] && {
    echo "${RTL_PRESENT_INDICATOR_FILE}"
    exit 0
}

[ "${1-}" = "--create" ] && {
    touch "${RTL_PRESENT_INDICATOR_FILE}"
    exit 0
}

sb=$(dp4-sb-root -s)
#echo_id sb
#echo_id RTL_SANDBOXES
vsetp "${RTL_SANDBOXES-}" && {
    case "${RTL_SANDBOXES}" in
        :$sb:) exit 0;;
    esac
}
 
mecd ap
[ -e "${RTL_PRESENT_INDICATOR_FILE}" ] && exit 0

exit 1   
