#!/bin/sh

source script-x
source eexec
set -u
progname="$(basename $0)"

was=$(pwd)
mecd testgen
[ "${was}" = "$(pwd)" ] || {
    echo "Changed to testgen dir."
}

: ${mdiag_more=}
: ${mdiag_args=}
: ${tgen_prog="./tgen.pl"}
: ${axf_p=}
: ${axf_plugin_bin=""}
: ${axf_cpu_model=0}
: ${axf_mdiag_args="-force_sockserv -reserve_sysmem 258 -top -sec_elf_name $(realpath $(pwd)/../../drv/mpcore/t124/ObjLinux_MPCoreXC/boot_page_table.axf) -cpu_model ${axf_cpu_model}"}
: ${rtl_args=-simv top_peatrans_gpurtl}
: ${rtl_args_more=}
: ${clib_linux=$(realpath "$(pwd)/../../clib/Linux")}
: ${d_path="$(pwd)/../../"}
: ${d_opt=""}
: ${last_and_latest_p=t}
: ${last_out_dir_file_name=last_out_dir}
: ${latest_out_dir_file_name=latest_out_dir}
: ${last_and_latest_prefix=}
: ${hist_file_name=$(basename $0).hist}
: ${mailto_opt=}

# Usage variable usage:
Usage_args_info=" <tgen-level-test>..."
Usage_synopsis="Run tgen levels one at a time using a consistent set of vars.
See also tgen.pl and testgen.pl for additional ops.
AXF options apply to all <tgen-level-test>s.
"
Usage_details="${EExec_parse_usage}
-w) Wait for completion rather than submitting to LSF.
-T <tgen-opt>) Add value to an additional string of tgen options.
-C) Clear clobber opt.
-l <level>) Specify tgen level file.
-r <trace-root>) Root for traces.
-c <chip>) Chip name/type.
-t <target>) E.g. FMODEL.
-d <???>) Default is hwApPath=\$(pwd)/../../ [${d_opt}]
--wait) Run synchronously. Implies --nomail. --mail after this will override.
--status) Print status after a sync run.
--wait-status|--status-wait|--ws) --wait and --status.
--nomail) No status/results mail is sent upon completion.
--mail) Not --nomail.
--mail-to|--mailto <addr>) Set email address.
--mail-me|--mailme) Add myself back in when --mail-to is used.
--mdiag-more|--md-more) <arg> Speciy mdiag args.
--dump-images) -dumpImages to trace3d.
"
# Example of arg parsing.
option_str="${EExec_parse_option_str}wT:Cl:r:c:t:d:"
long_options=("wait"
"tgen-opt:"
"clobber"
"level:"
"trace-root:"
"chip:"
"target:"
"log-dir:"
"log-base:"
"status"
"status-wait" "wait-status" "ws"
"mdiag-args:"
"mdiag-more:" "md-more:"
"dump-images"
"nomail"
"mail-to:" "mailto:"
"mail-me" "mailme"
"all-but-run" "abr" "no-run"
"axf"
"axf-bin:" "axf-exe:" "axf-prog:" "--axf-plugin:"
"rtl"
"rtl-args-more:"
"start-record:"
"queue:"
"split-waveform" "div-waveform"
"no-last" "no-latest"
"last-out-dir:" "latest-out-dir:"
"last-and-latest-prefix:" "ll-prefix:"
"mail")

: ${default_level=$(pwd)/config/levels/tegra/regress_tegra_gpu_multiengine}
: ${user_levels=}
: ${user_tgen_opts=}
: ${mail_opt=}                  # Whatever tgen*'s default is.

source dp-getopt+.sh
for i in "$@"
do
  # do. e.g.  $OPTION_ARG=$2; shift;; to process options with arguments.
  case $1 in
      # eexec support
      -n) EXEC=echo; EExecDashN;; # Don't actually execute stuff
      -v) VERBOSE="echo $progname: "; EExecVerbose;;
      -q) VERBOSE=":"; EExecQuiet;;

      # Program options.
      # No mail if we're waiting. Can be turned on by a following --mail.
      -w|--wait) wait_opt=-wait; mail_opt="-nomail";;
      -T|--tegn-opt) shift; user_tgen_opts="$user_tgen_opts $1";;
      -C|--clobber) clobber_opt=;;
      -l|--level) shift; llist=$(echo "$1" | sed -r 's/,/ /g')
                  user_levels="${user_levels} ${llist}";;
      -r|--trace-root) shift; traceRoot_opt="$1";;
      -c|--chip) shift; chip_opt="$1";;
      -t|--target) shift; target_opt="$1";;
      --all-but-run|--abr|--no-run) all_but_run_opt="-allButRun";;
      -d) shift; d_path="$1";;
      --log-dir) shift; user_log_dir="$1";;
      --log-base) shift; log_dir_base="$1";;
      --wait-status|--status-wait|--ws) wait_opt="-wait"; mail_opt='-nomail';
                                        display_status_p=t;;
      --mdiag-more|--md-more) shift; mdiag_more="$mdiag_more $1";;
      --mdiag-args|--md-args) shift; mdiag_args="$1";;
      --dump-images) mdiag_more="$mdiag_more -dumpImages";;
      --status) display_status_p=t;;
      --nomail) mail_opt=;;
      --mail) mail_opt="-mail";;
      --mail-to|--mailto) shift; mailto_opt="${mailto_opt} -mailto ${1}";;
      --mail-me|--mailme) mailto_opt="${mailto_opt} -mailto ${USER}";;
      --axf) axf_p=t;;
      --axf-bin|--axf-exe|--axf-prog|--axf-plugin) shift; axf_plugin_bin="${1}"; axf_p=t;;
      --rtl) rtl_p=t;;
      --rtl-args-more) shift; rtl_args_more="${rtl_args_more} ${2}";;
      --start-record) rtl_args_more="${rtl_args_more} +startrecord+${1}";;
      --split-waveform|--div-waveform) rtl_args_more="${rtl_args_more} +fsdbAutoSwitch";;
      --queue) shift; queue="$1";;
      --no-last|--no-latest) last_and_latest_p=;;
      --last-out-dir) shift; last_out_dir_file_name="${1}";;
      --latest-out-dir) shift; latest_out_dir_file_name="${1}";;
      --last-and-latest-prefix|--ll-prefix) shift; last_and_latest_prefix="${1}";;
      # Help!
      --help) Usage; exit 0;;
      --) shift ; break ;;
      *) echo 1>&2 "Unsupported option>$1<"
         exit 1;;
    esac
    shift
done
# The following is needed only when non optional args are required.
[ "$*" = "" ] && {
    Usage "Test name[s] are required."
    exit 1
}

: ${wait_opt=}
: ${tgen_opts=${user_tgen_opts}}
: ${clobber_opt=-clobber}
: ${levels:=${user_levels:-${default_level}}}
: ${traceRoot_opt=/home/scratch.traces02/arch/traces/}
: ${chip_opt=t124}
: ${target_opt=FMODEL}
: ${user_log_dir=}
: ${log_dir_base=dp-run-tgens.d} # This is duplicated in tgen-latest-run. Make a tgen.rc type file.
: ${log_dir=${user_log_dir}}
: ${display_status_p=}
: ${all_but_run_opt=}
: ${rtl_p=}
: ${queue=}

# Common timestamp
timestamp=$(dp-std-timestamp)

vunsetp "$levels}" && {
    Usage "At least one level is needed."
    exit 1
}

if vunsetp "$user_log_dir"
then
    log_dir="$log_dir_base"
else
    log_dir="${user_log_dir}"
fi
log_dir=$(normpath "$log_dir")
EExec mkdir -p $(dirname "$log_dir")
hist_file=$(normpath "${log_dir}/${hist_file_name}")

dollar_at=("$@")

set --

vsetp "${rtl_p}" && {
    target_opt=RTL
    set -- "$@" ${rtl_args}
}

vsetp "${d_opt}" || {
    d_opt="hwApPath=$(realpath ${d_path})"
}
d_opt=$(normpath "${d_opt}")/

# Appending to $@ allows for more kinds of quoting to be preserved.
vsetp "${queue}" && set -- "$@" -queue "${queue}"
vsetp "$traceRoot_opt}" ] && set -- "$@" -traceRoot "${traceRoot_opt}"
vsetp "$chip_opt}"  && set -- "$@" -chip "${chip_opt}"
vsetp "$target_opt}"  && set -- "$@" -target "${target_opt}"
vsetp "$d_opt}" ] && set -- "$@" -d "${d_opt}"
vsetp "${all_but_run_opt}" && set -- "$@" "${all_but_run_opt}"
vsetp "${mailto_opt}" && set -- "$@" ${mailto_opt}
log_prefix="$log_dir"

[ -n "$display_status_p" -a -z "$wait_opt" ] && {
    echo "WARNING: display status and wait do not play well together."
} 1>&2

EExec_verbose_echo_id levels

if EExecDashN_p
then
    eexec_dash_n_prefix="{-}"
else
    eexec_dash_n_prefix=""
fi

base_dollar_at=("$@")
for level in $levels
do
  level_opt="-level $level"
  EExec_verbose_echo_id level
  for test_name in "${dollar_at[@]}"
  do
    EExec_verbose_echo_id test_name
    set -- "${base_dollar_at[@]}" -level "${level}"

    [ "${test_name}" = 'all' ] || set -- "$@" -only "${test_name}"
    vsetp "$mdiag_more" && set -- "$@" -mdiagArgsMore "${mdiag_more}"
    vsetp "${axf_p}" && mdiag_args="${mdiag_args} ${axf_mdiag_args}"
    vsetp "${axf_plugin_bin}" && {
        case "${axf_plugin_bin}" in
            *.axf) ;;
            *) axf_plugin_bin="${axf_plugin_bin}.axf";;
        esac
        
        case "${axf_plugin_bin}" in
            */*) ;; # Assume any slash means the full pathname has been given.
            *) axf_plugin_bin="${clib_linux}/${axf_plugin_bin}";;
        esac
        [ -e "${axf_plugin_bin}" ] || {
            echo "$progname: axf plugin [$axf_plugin_bin] doesn't exist."
            exit 1
        } 1>&2
        mdiag_args="${mdiag_args} -plugin ${axf_plugin_bin}"
    }

    vsetp "$mdiag_args" && set -- "$@" -mdiagArgs "${mdiag_args}"
    vsetp "${clobber_opt}" && set -- "$@" -clobber
    set -- "${tgen_prog}" "$@"

    # Can't create out_dir and put this in it because tgen will complain the
    # dir exists if -clobber is not used and if -clobber is used, the
    # directory will be nuked first.
    # Could put another layer under which the command line file can live next to the tgen output dir.
    if vsetp "${user_log_dir}"
    then
        out_dir="${user_log_dir}"
    else
        out_dir="${log_prefix}/${test_name}/${timestamp}${wait_opt}.out"
    fi
    out_dir=$(normpath -r "${out_dir}")

    EExec_verbose_echo_id out_dir
    set -- "$@" -outDir "${out_dir}"

    if [ "${last_and_latest_prefix}" = "." ]
    then
        ll_prefix="${test_name}."
    else
        ll_prefix="${last_and_latest_prefix}"
    fi

    last_out="${ll_prefix}${last_out_dir_file_name}"
    latest_out="${ll_prefix}${latest_out_dir_file_name}"
    echo_id last_out
    echo_id latest_out

    if ! EExecDashN_p
    then
        EExec mkdir -p $(dirname "${out_dir}")
        vsetp "${last_and_latest_p}" && {
            # Keep a history with latest last.
            # The script below now tails the last line.
            echo "$out_dir" >> "${last_out}"
            echo "#!/bin/sh
tail -n1 ${last_out_dir_file_name}" >| "${latest_out}"
            chmod +x "${latest_out}"
        }
        command_line_log="${out_dir}.command-line"
        EExec_verbose_echo_id command_line_log
        echo "$@" > "${command_line_log}"
    fi
    echo "${eexec_dash_n_prefix}${level}::${test_name} --> ${out_dir}" >> "${hist_file}"
    # EExecDashV_p && EExec -y -0 eko "EExec eko: $@"
    EExec "$@"
    
    [ -n "${display_status_p}" ] && {
        EExec ./batch_status "${out_dir}"
    }
    echo_id out_dir
  done
done

vsetp "${all_but_run_opt}" && {
    echo "
*** $progname: -allButRun was used.
  Don't forget to run them if you need to."
} 1>&2
