#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

# 
# Print detailed information about a sandbox
#

sb="${1-}"
if vsetp "$sb"
then
    case "${sb}" in
        -|*|all|everything) sb="sb1 sb2 sb3 sb4 sb5";;
        *) sb="$@";;
    esac
else
    sb=$(basename $(dirname $(me-expand-dest)))
fi

echo_id sb

for s in $sb
do
  echo_id_ornate s
  set +u
  eval sb_dir=\$$s
  set -u
  echo_id sb_dir
  vunsetp $sb_dir && {
      echo "$s doesn't seem to be defined."
      echo -------
      echo
      continue
  } 1>&2
  df -h "${sb_dir}"
  
  case "$s" in
      sb1) info="DEP_CPU.
Available.
*** Not built with RTL.
"
      ;;
      sb2) info="DEP CPU
Build with RTL.
Others to come.
"
      ;;
      sb3) info="Surface_write_read on TOP RTL.
Replaced sb5 when sb5 had problems running GPU RTL.
This is now the real Surface_write_read dev dir.
"
      ;;
      sb4) info="Unused.
"
      ;;
      sb5) info="Old Surface_write_read on TOP RTL
Useful for throw away stuff until needed.
"
      ;;
      *) echo 1>&2 "Unknown sandbox>$sb<"; exit 1;;
  esac
  echo "$info"
  (g "${s}" >/dev/null; echo "sandbox root dir: $(pwd)";  p4 opened)
done

exit 0
