#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

EExec -y cd $(me-dogo ap)
EExec_verbose_msg "cwd>$(pwd)<"

echo "bin/t_make $@" | EExec tcsh_run ${dash_n}

