#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${purge_p=t}

[ "${1-}" = "--no-purge" ] && {
    purge_p=
    shift
}

EExec -y mecd testgen

EExec ./build_gpu_multiengine.pl purge \
   && {
          echo "***** Purge Complete *****"
          EExec ./build_gpu_multiengine.pl -debug=1 \
          && {
                  echo "***** Build Complete *****"
                  vsetp "${send_mail_on_completion-}" && {
                      mail -s "$progname is done" "${USER}" < /dev/null >/dev/null 2>&1
                  }
                  vsetp "${send_mail_on_completion-}" && {
                      mail -s "$progname is done" "${USER}" < /dev/null >/dev/null 2>&1
                  }
                  exit 0
          }
   }

echo 1>&2 "Failed somewhere."
