#!/bin/sh

source maybe-davep

# Run a test looking for common stupid errors that should have been fixed long ago.
# And some of mine as well.
# Check for a (gdb) prompt to let me know if I'm running a test that I've set
# up to run under gdb. When this happens the test hangs because gdb is
# waiting for input. I could just send a 'run' command, but I prefer to know
# and exit so I can do it right.

# any_shell_p=t defaults to true in my environment.
echo_id any_shell_p
$EEXEC tgen-run-dot-sh-logged \
    ${maybe_davep_dash_n} \
    --hgrep surface_write_read: \
    --egrep 'Error opening.*\.so:.*lib.*not found|ERROR: cannot aquire /tmp/asim.X|something bad happened|\(gdb\)' \
    --hgrep 'RT_FAIL' \
    --hgrep 'call stack' \
    "$@"
