#!/bin/sh

source script-x
source eexec
set -u
progname="$(basename $0)"

eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done

test_name="$1"

out_dir="$test_name.$(dp-std-timestamp)"

echo ./tgen.pl \
   -target FMODEL \
   -chip t124 \
   -level $(pwd)/config/levels/tegra/regress_tegra_gpu_multiengine \
   -d hwApPath=$(pwd)/../../ \
   -traceRoot /home/scratch.traces02/arch/traces/ \
   -only "$test_name" \
   -outDir "$out_dir" \
   -clobber
