#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

mecd testgen

vunsetp "$*" && {
    set -- $(./latest_out_dir)
}

for dir in "$@"
do
  echo "run dir: $dir"
  ./batch_status "${dir}"
done
