#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

[ "$#" = 0 ] && {
    echo "usage: $progname plugin-name"
    exit 1
}

exit 99

plugin="${1}"

EExec bin/system_run \
    -mode arm \
    -P t124 \
    -dir TEST_DIR \
    -noClean \
    -o TEST_DIR/simfront.log \
    -traces ../../arch/traces/mobile/traces/gpu_multiengine \
    -mods "-top -cpu_rtl -no_check -pitch -zt_count_0 -trace kepler_b/ogtest/comp_one_tri -plugin '${plugin}'" \
    ${plugin}.so \
    -v top_peatrans_gpurtl

