#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

: ${base=t124_debug}

[ -n "${1-}" ] && {
    d="${1}"
    [ -f "${d}" ] && {
        d=$(dirname "${d}")
    }
    cd "$d"
}

makefile=$(find-up Makefile)
mf_dir=$(dirname "${makefile}")
mf_rel_dir=$(tot-relative "${mf_dir}")

tmake_job=$(namify-path -c_ "${mf_rel_dir}")

[ -n "${base}" ] && {
    tmake_job="${base}_${tmake_job}"
}

EExec_verbose_msg "tmake_job>$tmake_job<"

EExec -y cd $(me-dogo tot)
EExec bin/t_make -only "${tmake_job}"

mecd tg
EExec_verbose_msg "pwd>$(pwd)<"

EExec ./build_gpu_multiengine.pl purge
EExec ./build_gpu_multiengine.pl -debug=1

