#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

dir=${1-$PWD}

tot=$(realpath $(depth))
rpwd=$(realpath "${dir}")

[ "${tot}" = "${rpwd}" ] && {
    # We are at tot.
    exit 0
}
rel=$(echo "${rpwd}" | sed -rn 's!^('"${tot}"'/)(.*)$!\2!p')

[ -z "$rel" ] && {
    echo "$progname: problem relativizing ${dir} to ${tot}."
    exit 1
} 1>&2

echo $rel
exit 0

