#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
if vsetp "${eexec_program-}"    # Did the caller provide a program?
then
    EEXEC_SHIFT=:
else
    eexec_program=$(EExec_parse "$@")
    EEXEC_SHIFT=shift
fi

for op in $eexec_program
do
  $op
  ${EEXEC_SHIFT}
done
unset eexec_program
# Or export eexec_program to propagate eexec info to a called program.
# export eexec_program

: ${tot=}
: ${yopp_p=}

while (($# > 0))
do
  case "$1" in 
      --yopp|-y) yopp_p=t;;
      --tot) shift; tot="${1}";;
      --) shift; break;;
      *) break;;
  esac
  shift
done

tot=$(me-expand-dest tot)
vsetp "${tot}" || {
    echo "Can't find tot>${tot}< dir."
    exit 1
} 1>&2

totbin="${tot}/bin"
[ -d "${totbin}" ] || {
    echo "${totbin} isn't."
    exit 1
} 1>&2

totbinmake="${totbin}/make"
[ -x "${totbinmake}" ] || {
    echo "${totbinmake} isn't."
    exit 1
} 1>&2

EExec_verbose_msg "making in PWD>$PWD<"
EExec "${totbinmake}" "$@"
true_p "${yopp_p}" && EExec email-yopp totmake: \""${totbinmake}" "$@"\" is done.
true_p "${yopp_p}" && EExec email-yopp totmake: \""${totbinmake}" "$@"\" is done.
