#!/bin/sh

source script-x
set -u
progname="$(basename $0)"
source eexec
eexec_program=$(EExec_parse "$@")
for op in $eexec_program
do
  $op
  shift
done
unset eexec_program

EExec ./configure --enable-option-checking=no --x-libraries=/usr/X11R6/lib64 --without-debug --with-error-checking=none --with-optimization --disable-kkcc --without-newgc --with-dlmalloc --with-zlib --with-x11 --with-database=none --with-infodock --with-mule --with-canna=no --with-wnn=no --with-wnn6=no --enable-toolbars=no --prefix=/home/dpanariti/yokel --with-site-lisp=yes --with-site-modules=yes --with-infopath=/home/dpanariti/yokel/lib/xemacs/info:/home/dpanariti/yokel/info:/usr/info/X11:/usr/info:/usr/local/lib/texmf/doc/info:/usr/lib/texmf/doc:/usr/share/info --enable-clash-detection --enable-athena=3d --enable-toolbars=no --enable-pdump
