#!/bin/sh
#set -x

exit 0

. $HOME/etc/crontab.rc
cd $ETC_BIN_DIR

# I'm looking at strigi now.
# Which can apparently do everything but function.
# so... back to the dog:
###vsetp dp_enable_beagle_p && dp-start-beagle

# been a while. look @ strigi again.  Beagle results seem to be nigh worthless.
