--- ./modules/c-animation/Makefile.ORIG	Tue Nov 26 16:38:15 2002
+++ ./modules/c-animation/Makefile	Tue Nov 26 16:50:49 2002
@@ -403,13 +403,13 @@
 
 
 %.x %.doc: %.c
-	$(SCWM_SRC_DIR)/scwm-snarf $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).x && \
-	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).doc \
+	$(SCWM_SRC_DIR)/scwm-snarf $< $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)  > $(basename $<).x && \
+	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf $< $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) > $(basename $<).doc \
 	|| { rm $(basename $<).x $(basename $<).doc ; false; }
 
 %.x %.doc: %.cc
 	CC=$(CXX) \
-	$(SCWM_SRC_DIR)/scwm-snarf -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).x && \
+	$(SCWM_SRC_DIR)/scwm-snarf $< -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) > $(basename $<).x && \
 	$(SCWM_BUILDSRC_DIR)/scwm-doc-snarf -DGUILE_CPLUSPLUS_SNARF $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $< > $(basename $<).doc \
 	|| { rm $(basename $<).x $(basename $<).doc ; false; }
 
