#!/usr/bin/env bash
#set -x

. script-x

dummy=
option_str='nd:s:DM'

#echo "PATH>$PATH<"
# needed on Linux when called from my account with sudo,e.g.:
#  sudo cd-burn
# for some reason, some of env isn't passed.
# ??? path changed in root's .bashrc?
# yep..., I've modified root's .bashrc on baloo.
PATH="/usr/yokel/sbin:/usr/yokel/bin:$HOME/bin:$PATH"
#echo "PATH>$PATH<"
#echo $HOME

[ -z "$HOST_INFO" ] && {
    rcfile="$HOME/.bashrc"
    [ -f $rcfile ] && . $rcfile
}

Usage()
{
    locat rc=$1
    echo 1>&2 "placeholder
$(basename $0) [-[$option_str]]"
    exit $rc
}

. eexec 
EExecEcho=echo

# simple front end to provide all of the params to cdrecord

# get defaults...
. cdrw.conf

##obs#args=$( getopt $option_str $* )
q=$(getopt $getopt_args -o "$all_options" -- "$@")
[ $? != 0 ] && Usage
eval set -- "$q"

[ $? != 0 ] && Usage

set -- $args
for i in $*
do
    case $1 in
	-n) EExecDashN;;
	-d) dev=$2; shift;;
	-D) dummy='-dummy';;
	-M) multi='';;
	-s) speed=$2; shift;;
	--) shift ; break ;;
	*) 
	    echo 1>&2 "Unsupported option>$1<";
	    exit 1 ;;
    esac
    shift
done

EExec cdrecord -v $dummy $multi $data fs=$fs speed=$speed dev="$dev" "$@"
