#!/bin/sh

# If there is a global system configuration file, suck it in.
#
if [ -r /etc/defaults/rc.conf ]; then
	. /etc/defaults/rc.conf
	source_rc_confs
elif [ -r /etc/rc.conf ]; then
	. /etc/rc.conf
fi

# Make shared lib searching a little faster.  Leave /usr/lib first if you
# add your own entries or you may come to grief.
#
if [ -x /sbin/ldconfig ]; then
	case `/usr/bin/objformat` in
	elf)
		_LDC=/usr/lib
		for i in ${ldconfig_paths}; do
			if [ -d "${i}" ]; then
				_LDC="${_LDC} ${i}"
			fi
		done
		echo 'setting ELF ldconfig path:' ${_LDC}
		ldconfig -elf ${_LDC}
		;;
	esac

	# Legacy aout support for i386 only
	case `sysctl -n hw.machine` in
	i386)
		# Default the a.out ldconfig path.
		: ${ldconfig_paths_aout=${ldconfig_paths}}
		_LDC=/usr/lib/aout
		for i in ${ldconfig_paths_aout}; do
			if [ -d "${i}" ]; then
				_LDC="${_LDC} ${i}"
			fi
		done
		echo 'setting a.out ldconfig path:' ${_LDC}
		ldconfig -aout ${_LDC}
		;;
	esac
fi
